### ISSUE TITLE
space when using fluid on container

### ISSUE THREAD

**Issue by inventanew** [dylanmoz/glamorous-grid#1]
When I put <Container fluid> it goes full width but it leaves 24px margin on each side? how do I get rid of this space?

**Comment by dylanmoz** [comment]
Hey John! Thanks for posting this issue.

I was lazy to not put this into the docs, so I just added it. The grid is based off of a default grid "theme" that you can override using glamorous' `ThemeProvider`. Here's a link to some example code in the docs I just updated:

https://dylanmoz.github.io/glamorous-grid/#theme
